### ISSUE TITLE
Problems with MLFlow with Yolov8 in AzureML

### ISSUE THREAD

**Issue by Diegoigerencia** [ouphi/yolov8-with-azureml#1]
Hi, i haved develop a script and a job for submit a model of Yolov8 but I have an error so I want to know if do you have a develop with mlflow and I can use that in my project?

If you want see the problem this is the link of the issues in yolov8 that I did write https://github.com/ultralytics/ultralytics/issues/3477

**Comment by ouphi** [comment]
Hi @Diegoigerencia, note that after yolov8 version 8.0.133, you can enable the [yolov8 mlflow callback](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/callbacks/mlflow.py)
by having following libraries installed in your azureml environment:
```
azureml-mlflow==1.52.0
mlflow==2.4.2
```

With this solution you don't need to add any code to log your model with mlflow as the mlflow callback already takes care of it.
