### ISSUE TITLE
How can I use your work for yolov5 model deployment

### ISSUE THREAD

**Issue by abhi0928** [ouphi/yolov8-with-azureml#4]
HI,

Thanks for your work it looks really simple to understand and well-managed.
I am trying to deploy my custom-trained yolov5 model on azure and I found so many issues with the different methods I saw on the internet. can you guide me on how I can use your work to deploy my yolov5 model and what changes I need to make to it? also in the deployment.yaml file line 5, do I need to write it like (azureml: model_name:1) or (azureml:model_name:1). 

Thanks a lot for your work

**Comment by ouphi** [comment]
Hi @abhi0928 , thank you for reaching out. I appreciate that you find this repo useful.
Yes you can leverage this repo to deploy your yolov5 model but you would need to apply a few changes.
You can find below the description of the steps and changes you need to apply.

## 1 - Register your custom train model in AzureML
Go to your AzureML portal, Select the `Models` tab > `+ Register`. Select model type `Unspecified type`. Upload your custom model and choose a name for your model.
In the azureml/deployment.yaml edit the model to be `azureml:<your-model-name>:1`. The model name should be the name you used when you registered the model.

## 2 - Change the Dockerfile in the `inference-environment` folder to the following:

```Dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN TZ=Etc/UTC apt install -y tzdata
RUN apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++
RUN apt upgrade --no-install-recommends -y openssl tar
RUN pip install azureml-inference-server-http

WORKDIR /app
RUN git clone https://github.com/ultralytics/yolov5
RUN python3 -m pip install --upgrade pip wheel
RUN pip install --no-cache -r yolov5/requirements.txt albumentations comet gsutil notebook \
    coremltools onnx onnx-simplifier onnxruntime 'openvino-dev>=2023.0'
```

## 3 - Inference code
- Clone the yolov5 repoistory inside the inference-code folder. The yolov5 repo is required to run the inference.
- Change the `score.py` script to use yolov5, for example:

```python
import torch
import os
import json

def init():
    global model
    model_path = os.path.join(
        os.getenv("AZUREML_MODEL_DIR"), "yolov5s.pt" # you need to replace yolov5s.pt by the name of the custom model file you uploaded when you registered the model
    )
    model = torch.hub.load('yolov5', 'custom', path=model_path, source='local')

def run(raw_data):
    image_url = json.loads(raw_data)["image_url"]
    results = model(image_url)
    return results.pandas().xyxy[0].to_json(orient="records")
```

Then follow the [instructions to deploy the endpoint](https://github.com/ouphi/yolov8-with-azureml?tab=readme-ov-file#deploy-model-for-inference).

**Comment by ouphi** [comment]
Hi @abhi0928 did this solution work for you? Have you been able to deploy your custom-trained yolov5 model?

**Comment by abhi0928** [comment]
Yes @ouphi, it did work for me I am able to deploy my model on azure, right now I am doing some changes so that I can deploy an ensemble model in there.
Thanks a lot for your help

**Comment by ouphi** [comment]
Great to hear! Since it's working for you, I'll go ahead and close the issue. :)
